### ISSUE TITLE
Conflict with ActiveStorage

### ISSUE THREAD

**Issue by scarroll32** [epfl-exts/rails-gdpr-export#1]
I had some trouble with ActiveStorage and the GDPR export gem, and in fact logged it with the Rails core team. 
https://github.com/rails/rails/issues/32933

They finally replied saying we should not use models in initialisers 

> There are two problem on loading Active Record models in initializers, one of them is that it will mess with the code reload, those models may not be able to be reloaded anymore.

In the end I followed this gem's code and modified the approach for [crowdAI](https://github.com/crowdAI/crowdai)

- [Initializer](https://github.com/crowdAI/crowdai/blob/master/config/initializers/gdpr.rb)
- [Export code: in the mailer - could be extracted](https://github.com/crowdAI/crowdai/blob/master/app/mailers/gdpr_export_mailer.rb#L65-L87)
- [Tests](https://github.com/crowdAI/crowdai/blob/master/spec/mailers/gdpr_export_mailer_spec.rb)

**Comment by grischoun** [comment]
Thanks for the update, Sean.
Nice solution you have!
I will update this gem's README with regard to the initialiser issue.
