### ISSUE TITLE
when renaming attributes they are doubled in csv file

### ISSUE THREAD

**Issue by balakirevs** [epfl-exts/rails-gdpr-export#2]
Could you check please, the renamed attributed are placed at the end of csv, though the original ones are also present.

**Comment by grischoun** [comment]
Do you have the attribute present twice in the gdpr_collect declaration? I.e., the original one at the beginning and the renamed one in the 'renamed fields' section.
If so, then just removed the original one and you won't see a duplicate in the csv.

**Comment by balakirevs** [comment]
:)
thanks!
